version: "3"
services:
  aswu:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - "./config.json:/config.json"
  aswupostgres:
    image: "postgres:16"
    deploy:
      mode: "global"
      restart_policy:
        delay: "1s"
        max_attempts: 3
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
